INSERT INTO label (name, mail, creation_date) VALUES ("Hot Creations", "cristianhuichaqueo@gmail.com", NOW());
INSERT INTO label (name, mail, creation_date) VALUES ("Mother Recordings", "cristianhuichaqueo@gmail.com", NOW());
INSERT INTO label (name, mail, creation_date) VALUES ("DIRTYBIRD", "cristianhuichaqueo@gmail.com", NOW());
INSERT INTO label (name, mail, creation_date) VALUES ("Sola", "cristianhuichaqueo@gmail.com", NOW());
INSERT INTO label (name, mail, creation_date) VALUES ("Solid Grooves Records", "cristianhuichaqueo@gmail.com", NOW());
INSERT INTO label (name, mail, creation_date) VALUES ("Pryda Recordings", "cristianhuichaqueo@gmail.com", NOW());
INSERT INTO label (name, mail, creation_date) VALUES ("ELEVATE", "cristianhuichaqueo@gmail.com", NOW());
INSERT INTO label (name, mail, creation_date) VALUES ("Relief", "alnocetti@gmail.com", NOW());
INSERT INTO label (name, mail, creation_date) VALUES ("Defected", "eaiannicelli@gmail.com", NOW());
INSERT INTO label (name, mail, creation_date) VALUES ("Watergate Records", "nkuglien@gmail.com", NOW());

INSERT INTO genre (name, creation_date) VALUES ("Big Room", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Breaks", NOW());
INSERT INTO genre (name, creation_date) VALUES ("DJ Tools", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Dance", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Deep House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Drum & Bass", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Dubstep", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Electro House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Electronica / Downtempo", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Funk / Soul / Disco", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Funky / Groove / Jackin' House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Future House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Garage / Bassline / Grime", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Glitch Hop", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Hard Dance", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Hardcore / Hard Techno", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Hip-Hop / R&B", NOW());
INSERT INTO genre (name, creation_date) VALUES ("House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Indie Dance / Nu Disco", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Leftfield Bass", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Leftfield House & Techno", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Minimal / Deep Tech", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Progressive House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Psy-Trance", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Reggae / Dancehall / Dub", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Tech House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Techno", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Trance", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Trap / Future Bass", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Big Room", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Breaks", NOW());
INSERT INTO genre (name, creation_date) VALUES ("DJ Tools", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Dance", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Deep House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Drum & Bass", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Dubstep", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Electro House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Electronica / Downtempo", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Funk / Soul / Disco", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Funky / Groove / Jackin' House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Future House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Garage / Bassline / Grime", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Glitch Hop", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Hard Dance", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Hardcore / Hard Techno", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Hip-Hop / R&B", NOW());
INSERT INTO genre (name, creation_date) VALUES ("House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Indie Dance / Nu Disco", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Leftfield Bass", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Leftfield House & Techno", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Minimal / Deep Tech", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Progressive House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Psy-Trance", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Reggae / Dancehall / Dub", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Tech House", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Techno", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Trance", NOW());
INSERT INTO genre (name, creation_date) VALUES ("Trap / Future Bass", NOW());

INSERT INTO label_genre (label_id, genre_id) VALUES (1, 1);
INSERT INTO label_genre (label_id, genre_id) VALUES (1, 2);
INSERT INTO label_genre (label_id, genre_id) VALUES (1, 3);
INSERT INTO label_genre (label_id, genre_id) VALUES (1, 4);

INSERT INTO label_genre (label_id, genre_id) VALUES (2, 1);
INSERT INTO label_genre (label_id, genre_id) VALUES (2, 2);
INSERT INTO label_genre (label_id, genre_id) VALUES (2, 3);

INSERT INTO label_genre (label_id, genre_id) VALUES (3, 1);

INSERT INTO label_genre (label_id, genre_id) VALUES (4, 1);