
INSERT INTO label (name, email, creation_date) VALUES ('Hot Creations', 'cristianhuichaqueo@gmail.com', '16-11-2017');
INSERT INTO label (name, email, creation_date) VALUES ('Mother Recordings', 'cristianhuichaqueo@gmail.com', '16-11-2017');
INSERT INTO label (name, email, creation_date) VALUES ('DIRTYBIRD', 'cristianhuichaqueo@gmail.com', '16-11-2017');
INSERT INTO label (name, email, creation_date) VALUES ('Sola', 'cristianhuichaqueo@gmail.com', '16-11-2017');
INSERT INTO label (name, email, creation_date) VALUES ('Solid Grooves Records', 'cristianhuichaqueo@gmail.com', '16-11-2017');
INSERT INTO label (name, email, creation_date) VALUES ('Pryda Recordings', 'cristianhuichaqueo@gmail.com', '16-11-2017');
INSERT INTO label (name, email, creation_date) VALUES ('ELEVATE', 'cristianhuichaqueo@gmail.com', '16-11-2017');
INSERT INTO label (name, email, creation_date) VALUES ('Relief', 'alnocetti@gmail.com', '16-11-2017');
INSERT INTO label (name, email, creation_date) VALUES ('Defected', 'eaiannicelli@gmail.com', '16-11-2017');
INSERT INTO label (name, email, creation_date) VALUES ('Watergate Records', 'nkuglien@gmail.com', '16-11-2017');

INSERT INTO genre (name, creation_date) VALUES ('Big Room', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Breaks', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('DJ Tools', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Dance', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Deep House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Drum & Bass', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Dubstep', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Electro House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Electronica / Downtempo', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Funk / Soul / Disco', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Funky / Groove / Jackin/ House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Future House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Garage / Bassline / Grime', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Glitch Hop', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Hard Dance', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Hardcore / Hard Techno', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Hip-Hop / R&B', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Indie Dance / Nu Disco', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Leftfield Bass', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Leftfield House & Techno', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Minimal / Deep Tech', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Progressive House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Psy-Trance', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Reggae / Dancehall / Dub', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Tech House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Techno', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Trance', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Trap / Future Bass', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Big Room', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Breaks', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('DJ Tools', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Dance', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Deep House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Drum & Bass', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Dubstep', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Electro House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Electronica / Downtempo', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Funk / Soul / Disco', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Funky / Groove / Jackin / House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Future House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Garage / Bassline / Grime', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Glitch Hop', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Hard Dance', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Hardcore / Hard Techno', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Hip-Hop / R&B', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Indie Dance / Nu Disco', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Leftfield Bass', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Leftfield House & Techno', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Minimal / Deep Tech', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Progressive House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Psy-Trance', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Reggae / Dancehall / Dub', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Tech House', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Techno', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Trance', '16-11-2017');
INSERT INTO genre (name, creation_date) VALUES ('Trap / Future Bass', '16-11-2017');


INSERT INTO label_genre (label_id, genre_id) VALUES (1, 1);
INSERT INTO label_genre (label_id, genre_id) VALUES (1, 2);
INSERT INTO label_genre (label_id, genre_id) VALUES (1, 3);
INSERT INTO label_genre (label_id, genre_id) VALUES (1, 4);
INSERT INTO label_genre (label_id, genre_id) VALUES (2, 1);
INSERT INTO label_genre (label_id, genre_id) VALUES (2, 2);
INSERT INTO label_genre (label_id, genre_id) VALUES (2, 3);
INSERT INTO label_genre (label_id, genre_id) VALUES (3, 1);
INSERT INTO label_genre (label_id, genre_id) VALUES (4, 1);